### ISSUE TITLE
New release with unambiguous license

### ISSUE THREAD

**Issue by palmskog** [Matafou/LibHyps#11]
After the merging of #10, the licensing concerns in #8 should be addressed. However, the project still can't be easily packaged in a system like Debian, since there is no release (git tag) which has the licensing fixes.

How about releasing a new version (tag `libhyps-2.0.4`) that includes the licensing fixes? I can help out with packaging on opam and so on.

**Comment by Matafou** [comment]
Hi there. Sorry, I don't know why I am not noticed of message in github lately.
I will do it shortly. Sorry for the delay.

**Comment by Matafou** [comment]
Done now. Please tell me if I should make a PR on coq opam archive.

Release is [libhypps-2.0.6](https://github.com/Matafou/LibHyps/releases/tag/libhyps-2.0.6) since there are tags named 2.04 and 2.0.5. By the way I used only tags for the last opam updates. Is it bad practice?

**Comment by palmskog** [comment]
@Matafou I'll take care of packaging `libhyps-2.0.6` via opam and also the ping people who want to know about it.

Here is how tags and releases work on GitHub:
- tags in the repo are the underlying basis for releases.
- releases are "bells and whistles" that GitHub offer on top of existing tags, such as release notes. Any tag can be "lifted" to release status via GitHub's web interface.

I have one favor to ask: can you please change the release title here to "License changed fully to MIT": https://github.com/Matafou/LibHyps/releases/tag/libhyps-2.0.6

You can do this by going to the link and pressing the pen icon in the upper right corner.

**Comment by palmskog** [comment]
Ah, and regarding best practices: yes, it's nice to users to always do full releases whenever you do a tag. A release is more visible on the GitHub repository page and thus easier to find. But many projects skip them and not a whole lot is lost, assuming the tags are still packaged somewhere else.

**Comment by Matafou** [comment]
Oops indeed I messed up with license names. Changed now.
