### ISSUE TITLE
Error in LibHypsDemo.v

### ISSUE THREAD

**Issue by whonore** [Matafou/LibHyps#2]
Using Coq 8.9.0

`make` doesn't actually build LibHypsDemo.v. Adding `$(HIDE)$(TIMER) $(COQC) $(COQDEBUG) $(TIMING_ARG) $(COQFLAGS) $(COQLIBS) ./LibHyps/LibHypsDemo.v $(TIMING_EXTRA)` to Makefile.local causes it to fail with the following error:
```
File "./LibHyps/LibHypsDemo.v", line 268, characters 21-61:
Error:
In nested Ltac calls to "(tactic4) ;!; (tactic3)", 
"tac_new_hyps_rev" and "tac1" (bound to decompose [ ex and ]
h_ex_and_neq_true_andb_and_le_w_w_eq_w_x), last call failed.
The reference h_ex_and_neq_true_andb_and_le_w_w_eq_w_x was not found
in the current environment.
```

**Comment by Matafou** [comment]
Thanks for reporting, I thing it is working now. Please reopen if it doesn't.
