### ISSUE TITLE
coq-8.11 compatible release

### ISSUE THREAD

**Issue by vzaliva** [Matafou/LibHyps#4]
Please make a release compatible with Coq-8.11.
The current `master` branch seems to be compiling fine, so it is just a matter of making a release and updating OPAM package.
I can produce a PR for OPAM package update, but I need a release first. Thanks!

**Comment by Matafou** [comment]
Sorry for the late reply. I did some time ago. Currently doing this for 8.12.

**Comment by vzaliva** [comment]
It is not in OPAM as of right now: 
```
$ opam install coq-libhyps                                                          
The following actions will be performed:
  ↘ downgrade coq                  8.11.2 to 8.10.2
          [required by coq-libhyps]
```

**Comment by Matafou** [comment]
Mmh strange. Iupdated the opam file long ago. Maybe I need to do something else?

**Comment by vzaliva** [comment]
To update in OPAM you need to do a PR to update the following:

https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-libhyps/coq-libhyps.1.0.0/opam

**Comment by Matafou** [comment]
It should be ok now. I will probably make another update for 8.13.
P.

Le jeu. 9 juil. 2020 à 19:09, Vadim Zaliva <notifications@github.com> a
écrit :

**Comment by vzaliva** [comment]
Thanks!
