### ISSUE TITLE
Please create a tag for Coq 8.14 in Coq Platform 2021.11

### ISSUE THREAD

**Issue by MSoegtropIMC** [Matafou/LibHyps#6]
The Coq team released Coq 8.14+rc1 on September 17, 2021 and plans to release Coq 8.14.0 before October 31, 2021.
The corresponding Coq Platform release 2021.11 should be released before November 30, 2021.
It can be delayed in case of difficulties until January 31, 2022, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knoweldege the latest released version of your project (2.0.3) does not work with Coq 8.14+rc1.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI appears to test this project, but has some special handling for your project which makes it difficult to retrieve the commit it tests for your project.

Could you please create a tag, or communicate us any existing tag that works with Coq branch v8.14, preferably before November 15, 2021?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

The working branch of Coq Platform, which already supports Coq version 8.14+rc1, can be found here https://github.com/coq/platform/tree/main.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/139

**Comment by MSoegtropIMC** [comment]
Sorry for pushing you, but the Coq Platform release is due in about 2 weeks and I didn't hear back from you. The status - as far as I can tell - is still that this does not compile with Coq 8.14.0

**Comment by Zimmi48** [comment]
@Matafou ping: you might have missed this

**Comment by Matafou** [comment]
Sorry I will have a look at it now.

**Comment by Matafou** [comment]
I have found the bug and will submit a new version shortly? Thanks for pinging!

**Comment by MSoegtropIMC** [comment]
I say thank you for the quick work!

Please keep the issue open until I updated Coq Platform - I will close it then.

**Comment by Matafou** [comment]
I made a second PR to fix a bug introduced by the first one. As advised by @MSoegtropIMC I updated the package instead of creating a new one.

**Comment by MSoegtropIMC** [comment]
Thanks! I picked coq-libhyps-2.0.4 for the 2021.11 pick for Coq 8.14.0 and 8.13.2.
